### ISSUE TITLE
Merge request send multiple calls of same API to backend server

### ISSUE THREAD

**Issue by rushiweb90** [devopsfaith/krakend-ce#210] opened 2020-04-22 08:03 UTC
I have an endpoint declared in my JSON which has 2 backends and expecting merged responses of provided backends but it turns out that KrakenD is sending out 2 calls to each Backend and responding with only response of either of them randomly.

**Comment by amarktl** [comment] 2020-08-25 14:50
If both endpoints answer with the same JSON names in the objects the result will "merge" into one. I have the same requirement to get those elements in a collection.

like:

Answer from one endpoint

`{
    "Item": "abc4711",
    "Amount": "46",
    "Location": "TestCenter123"
}
`

answer from the other 

`{
    "Item": "abc4711",
    "Amount": "31",
    "Location": "TestCenter456"
}
`

`{
    "result": [
        {
            "Item": "abc4711",
            "Amount": "46",
            "Location": "TestCenter123"
        },
        {
            "Item": "abc4711",
            "Amount": "31",
            "Location": "TestCenter456"
        }
    ]
}
`

but i have not yet found out how to configure krakend to do this.

@kpacha could you provide a hint - please. :)

BR,
Alex

**Comment by amarktl** [comment] 2020-08-26 10:42
maybe this works when 1.2 is released which should include: https://github.com/devopsfaith/krakend-documentation/issues/77 
@kpacha , @alombarte  is there a roadmap when 1.2 will be released?
BR,
Alex

**Comment by kpacha** [comment] 2020-09-02 18:12
no, this is not a bug. it's the expected behaviour. the fastest response is being overwrite with the slowest one.

responses are merged, not appended, so you should add a group name for each response https://www.krakend.io/docs/endpoints/response-manipulation/#grouping so they don't collide

**Closed by kpacha** 2020-09-02 18:12 UTC
Labels: question
